### ISSUE TITLE
Set nginx keepalive_timeout to 300 seconds 

### ISSUE THREAD

**Issue by rjayasekera** [fecgov/fec-proxy#117]
We are trying to reduce no of 502 errors we are seeing on kibana logs in prod space. Currently nginx is using the default keepalive_timeout of 30 seconds since it is not specified in nginx config file.

Set nginx timeout as:
- [x] keepalive_timeout 300;
- [x] proxy_connect_timeout 300;
- [x] proxy_read_timeout 300;

And also set the API timeout to 300 as well
python manage.py cf_startup
- [x] gunicorn --access-logfile - --error-logfile - --log-level info --timeout 300 -k gevent -w 4 webservices.rest:app

Example of queries that time out after 30 seconds, currently in PROD environment:
https://api.open.fec.gov//v1/schedules/schedule_a/?sort_hide_null=false&api_key=DEMO_KEY&sort_nulls_last=false&two_year_transaction_period=2018&min_date=01%2F01%2F2017&max_date=12%2F31%2F2018&contributor_city=Wichita&contributor_state=KS&sort=-contribution_receipt_date&per_page=30&is_individual=true

**Comment by patphongs** [comment]
This is done, closing
