### ISSUE TITLE
Set up CircleCI for proxy

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-proxy#164]
We should set up CircleCI for proxy. This would make deploys/redeploys easier. There's a concern about downtime so we usually do this off-hours. I imagine Circle can schedule builds for certain times. Docs: https://circleci.com/docs/2.0/workflows/#nightly-example. We could do a nightly scheduled build, or hold for manual approval if we want closer supervision. This would still make the team process easier. With Circle, we could also probably test more easily if there is downtime.

- [x] Look at how fec-pattern-library is deployed with Circle
- [x] Set up workflow to require manual start? Schedule it for off-hours? Ask @patphongs 
- [x] Decide how to target different spaces - should we make `develop` and `release` branches and add it to our deployment cycles? ➡️ this is the only way I could figure out to do this. 
- [x] Check with the team to make sure it's ok to add proxy to deploy/release process. 
- [x] Talk to Pat and content team - going forward, redirect (and other) PR's should probably get merged to the (new) `develop` branch.
- [x] After this is merged, point redirect PRs to develop

**Comment by patphongs** [comment]
Moving this to PI 14 when we have more time

**Comment by lbeaufort** [comment]
PR merged to `develop` branch
