### ISSUE TITLE
Build warnings when deploying

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-proxy#169]
**What we're after:** This work has the potential to be problematic if/when something happens to the proxy. 

**Completion criteria:**
- [ ] Figure out how to upgrade and address both warnings
- [ ] Target dev space to test (dev manifest files)

Build warnings when deploying:

```
Downloaded app package (15.5K)
-----> Staticfile Buildpack version 1.5.5
-----> Installing nginx
    Using nginx version 1.17.9
-----> Installing nginx 1.17.9
    Download [https://buildpacks.cloudfoundry.org/dependencies/nginx-static/nginx-1.17.9-linux-x64-cflinuxfs3-d122d80d.tgz]
    **WARNING** nginx 1.17.x will no longer be available in new buildpacks released after 2020-05-01.
    See: https://nginx.org/
-----> Root folder /tmp/app
-----> Copying project files into public
-----> Configuring nginx
    **WARNING** overriding nginx.conf is deprecated and highly discouraged, as it breaks the functionality of the Staticfile and Staticfile.auth configuration directives. Please use the NGINX buildpack available at: https://github.com/cloudfoundry/nginx-buildpack
```
From the above error message, 
> Please use the NGINX buildpack available at: https://github.com/cloudfoundry/nginx-buildpack

More context on why using staticfile buildpack and custom nginx.conf (like we do): https://github.com/cloudfoundry/staticfile-buildpack/issues/144#issuecomment-379567823

**Comment by lbeaufort** [comment]
History: https://github.com/cloudfoundry/staticfile-buildpack/issues/144
https://docs.cloudfoundry.org/buildpacks/staticfile/index.html#configure

**Comment by lbeaufort** [comment]
```
Downloading nginx_buildpack...
Downloaded nginx_buildpack (8.9M)
Cell 666f4c22-43e5-4020-95f1-36eef13541b8 creating container for instance f193e3c0-823a-4990-9926-85694a03b5ed
Cell 666f4c22-43e5-4020-95f1-36eef13541b8 successfully created container for instance f193e3c0-823a-4990-9926-85694a03b5ed
Downloading app package...
Downloaded app package (16.2K)
-----> Nginx Buildpack version 1.1.7
-----> Supplying nginx
-----> No nginx version specified - using mainline => 1.17.9
-----> Installing nginx 1.17.9
       Download [https://buildpacks.cloudfoundry.org/dependencies/nginx/nginx-1.17.9-linux-x64-cflinuxfs3-9efdb551.tgz]
       **WARNING** nginx 1.17.x will no longer be available in new buildpacks released after 2020-05-01.
       See: https://nginx.org/
       **ERROR** nginx.conf file must be configured to respect the value of `{{port}}`
       **ERROR** Could not validate nginx.conf: no {{port}} in nginx.conf
Failed to compile droplet: Failed to run all supply scripts: exit status 14
Exit status 223
Cell 666f4c22-43e5-4020-95f1-36eef13541b8 stopping instance f193e3c0-823a-4990-9926-85694a03b5ed
Cell 666f4c22-43e5-4020-95f1-36eef13541b8 destroying container for instance f193e3c0-823a-4990-9926-85694a03b5ed
Cell 666f4c22-43e5-4020-95f1-36eef13541b8 successfully destroyed container for instance f193e3c0-823a-4990-9926-85694a03b5ed

Deleting app proxy in org fec-beta-fec / space dev as lbeaufort@fec.gov...
OK
Renaming app proxy-venerable to proxy in org fec-beta-fec / space dev as lbeaufort@fec.gov...
OK
error: BuildpackCompileFailed
```

**Comment by lbeaufort** [comment]
can validate with `brew install nginx` and `nginx -t -c /Users/lbeaufort/dev/fec-proxy/nginx.conf` but I'm not sure this is specific to the way the cf buildpack needs it

**Comment by lbeaufort** [comment]
Example conf files: 
https://github.com/cloud-gov/cf-subpath-proxy/blob/master/nginx.conf
https://github.com/cloudfoundry/nginx-buildpack/blob/master/fixtures/mainline/nginx.conf

**Comment by lbeaufort** [comment]
I’m thinking we need to accept this risk for now, since we’d need to completely re-write the proxy application and we don’t have that expertise, and might be riskier than just leaving it as-is until more people address this and we can look at their implementation. https://github.com/fecgov/fec-proxy/pull/174/files

**Comment by patphongs** [comment]
@lbeaufort From what I can gage, we use cloud.gov's staticfile_buildpack v1.5.5. That version utilizes [nginx version 1.17.9](https://github.com/cloudfoundry/staticfile-buildpack/releases). The latest version of staticfile_buildpack v1.5.7 is using nginx version 1.17.10. As long as cloud.gov does not upgrade their staticfile_buildpack to a future version that is incompatible with the version of nginx, I see this risk as low. We should be cognizant of when cloud.gov upgrades their staticfile_buildpack to ensure that there are no issues with the upgraded nginx version that is used.

**Comment by ChrisMcGowan** [comment]
Hi folks - so 1.5.7 is the current static-buildpack level - you can track new releases here : 

https://github.com/cloudfoundry/staticfile-buildpack/releases

From our cloud-foundry standpoint - new releases of buildpacks come in new releases of cf-deployment: 

https://github.com/cloudfoundry/cf-deployment/blob/master/cf-deployment.yml - look down under the `releases:` section of the file.

**Comment by lbeaufort** [comment]
Closing in favor of #200 - the version warnings no longer appear, but we should move over to the NGINX buildpack.
