### ISSUE TITLE
Redirect three e-regs to the e-cfr

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-proxy#273]
We need to update https://github.com/fecgov/fec-proxy/blob/develop/nginx.conf to exclude three e-regs that we are going to redirect to a federal register notice until we are able to update e-regs for 2021.

These three pages for regs (11 CFR 111.24, 111.43 and 111.44):
https://www.fec.gov/regulations/111-24/2020-annual-111
https://www.fec.gov/regulations/111-43/2020-annual-111
https://www.fec.gov/regulations/111-44/2020-annual-111

~will need to redirect to https://sers.fec.gov/fosers/showpdf.htm?docid=412715.~
will need to redirect to their ecfr pages:
https://www.ecfr.gov/cgi-bin/text-idx?SID=6f2b90c7c55a428fa3aaa938d6cd54c1&mc=true&node=se11.1.111_124&rgn=div8
https://www.ecfr.gov/cgi-bin/text-idx?SID=6f2b90c7c55a428fa3aaa938d6cd54c1&mc=true&node=se11.1.111_143&rgn=div8
https://www.ecfr.gov/cgi-bin/text-idx?SID=6f2b90c7c55a428fa3aaa938d6cd54c1&mc=true&node=se11.1.111_144&rgn=div8

### Action items
- [ ] Create new redirects file for /regulations

### Completion criteria
- [ ] The three regs above redirect to the 2021 FR notice of admin fines.
- [ ] ~Put in ticket to remove this redirect once the 2021 regulations are imported into eregs. (ticket is here: https://github.com/fecgov/fec-eregs/issues/580, should be a blocker to the new ticket)~ - Note- the 2021 admin fine rules did not make the 2021 11 CFR in time for GPO's cutoff date - we'll need to keep redirect in place until the 2022 regulations are imported into eregs.
- [ ] Put in a ticket to test this redirect after the release (or add to existing testing ticket)

**Comment by lbeaufort** [comment]
Testing URLs
https://dev.fec.gov/regulations/111-24/2020-annual-111
https://dev.fec.gov/regulations/111-43/2020-annual-111
https://dev.fec.gov/regulations/111-44/2020-annual-111

**Comment by lbeaufort** [comment]
PR merged to develop, going out in 15.1 release: https://github.com/fecgov/fec-proxy/pull/274
