### ISSUE TITLE
Update www redirects for guidance search files following implementation of site map

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-proxy#365]
After the site map is implemented, we need to implement redirects for the PDF and HTML files in there. Since the PDF files are in Wagtail, the redirects will be done via www.

Technical info:
[Code](https://github.com/fecgov/fec-proxy/blob/develop/redirects-www.conf)

Completion Criteria;
- [x] Redirects are merged
- [ ] Testing ticket created

**Comment by dorothyyeager** [comment]
I discovered some URLs had not been updated in the PR that was merged, probably because they were missed in the spreadsheet too. Have put in a PR to update that at https://github.com/fecgov/fec-proxy/issues/368. After that PR is merged and the testing ticket is created, this ticket can be closed.

**Comment by johnnyporkchops** [comment]
Complete
