### ISSUE TITLE
Redirect office pages from transition to new wagtail pages

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-proxy#398]
**What we're after:**
_As a user who wants to learn more about the different FEC offices and their leadership, I need to confidently find revised office pages._

Once the updated office pages are published, we'll need to redirect the old transition pages to the new ones in wagtail.

**Related issues:**
- #5426 

### Completion criteria
- [ ] Redirects for old office pages are merged
- [x] Redirect spreadsheet is updated
- [x] Testing ticket is created

### Future work
- Once redirects are tested and working, we'll add the office pages to a take-down ticket.

**Comment by dorothyyeager** [comment]
This ticket can be closed once the related PR at https://github.com/fecgov/fec-proxy/pull/399 is merged.

Testing ticket has been created for 24.5 and the redirect spreadsheet has been updated.

**Comment by dorothyyeager** [comment]
Have added section anchors to the redirects where it would be useful. Redirect spreadsheet updated. It's ready for review @patphongs
