### ISSUE TITLE
New Relic Error Reporting on Proxy

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-proxy#52]
Add error reporting on the fec-proxy instance.

**Comment by ccostino** [comment]
This entails adding New Relic monitoring to the proxy application (cited in https://github.com/18F/openFEC/issues/2561).

**Comment by ccostino** [comment]
It looks like we might need to add a plugin to nginx itself in order to setup monitoring:  https://newrelic.com/plugins/nginx-inc/13

**Comment by ccostino** [comment]
This seems to require having another module enabled within ngnix, the `HttpStubStatusModule` (some info/instructions here: https://easyengine.io/tutorials/nginx/status-page/); this module is enabled in our setup but there's some additional configuration needed.  Given the potential to expose some information, I'm asking the cloud.gov team first to see if this is an appropriate path forward to enabling this or if there's another way we should be going about this instead (or if this is simply not possible).

**Comment by ccostino** [comment]
Unfortunately it looks like setting up that plugin won't be an option, though a couple of folks on the cloud.gov team are going to investigate a bit more.  In the meantime, we could setup basic monitoring via the `Synthetics` module in New Relic to point to a page served by the proxy app and at least see if any errors are being returned.

Will this be enough for us in this case?  If we were to set something up that just points to `http://www.fec.gov/` and check for status codes returned (and, if possible, response times), will this give us the monitoring and alerts we're looking for with the proxy app?  Or were folks expecting something more comprehensive like the monitoring and alerting we see for the other applications?

**Comment by LindsayYoung** [comment]
The idea in this ticket was trying to have better tools to see if errors are coming form the proxy rather than the underlying apps. We would be a page served by the proxy app and not just proxied content. That way, we would have a ping that would only error if there was an issue with the proxy. (We already have pings on many things that are served by the proxy including the home page.)

**Comment by ccostino** [comment]
Okay sounds good, thanks @LindsayYoung!  So the tasks become these:

* [ ] Create a page/JSON snippet served directly by the proxy app itself
* [ ] Set up a Synthetic in New Relic to ping that proxy-specific URI specifically

Sound good to everyone?
