### ISSUE TITLE
Change nginx timeout to 60 seconds to match CMS timeout

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-proxy#72]
Per our engineering sync on 2/16, we should change the `nginx` timeout to 60 seconds to match CMS timeout.

- [x] Update the timeout [here](https://github.com/fecgov/fec-proxy/blob/master/nginx.conf#L23) to 60 seconds to match the CMS 60-second timeout

cc: @patphongs 

Testing notes: https://github.com/fecgov/fec-proxy/issues/72#issuecomment-366310894
- [x] Update & [manual deploy](https://github.com/fecgov/fec-proxy#deploy) to `dev`, test 
- [x] Update &  [manual deploy](https://github.com/fecgov/fec-proxy#deploy) to `stage`, test 
- [x] Update &  [manual deploy](https://github.com/fecgov/fec-proxy#deploy) to `prod`

**Comment by patphongs** [comment]
This link file was consistently failing to download so we can try to test on that in dev: http://fec-dev-proxy.app.cloud.gov/files/bulk-downloads/2016/indiv16.zip I'm not sure if increasing the timeout will solve this particular download problem as the file is quite large and may take longer to download, but we can use it as a baseline to see that it's actually timing out at 60 seconds.

Any other links that consistently take longer to query we'll want to try testing too, looking through the Kibana logs as to what those queries are will help with testing.

FYI, I wrote a wiki as to how to retrieve S3 bulk downloads here: https://github.com/18F/fec-cms/wiki/Retrieving-S3-bulk-download-files

**Comment by LindsayYoung** [comment]
Updated the bulk download to have a keepalive_timeout of 180. That will allow all the files to download.

**Comment by LindsayYoung** [comment]
I got the test file to work on dev but it timed out on me for prod.

**Comment by rjayasekera** [comment]
I was trying to download the test file
http://fec-dev-proxy.app.cloud.gov/files/bulk-downloads/2016/indiv16.zip

200 GET /files/bulk-downloads/2016/indiv16.zip (18737.564 ms)

2018/02/25 11:19:54 [crit] 46#0: *6180 pwritev() "/home/vcap/app/nginx/proxy_temp/0/02/0000000020" failed (28: **No space left on device**) while reading upstream, client: 10.10.1.71, server: localhost, request: "GET /files/bulk-downloads/2016/indiv16.zip HTTP/1.1", upstream: "https://52.92.252.4:443/bulk-downloads/2016/indiv16.zip", host: "fec-dev-proxy.app.cloud.gov"

vcap@02326fce-b56f-46e8-641a-6a3f:~/app/nginx/proxy_temp$ df -h

Filesystem   |   Size | Used | Avail | Use% | Mounted on
------ | ------ | ------ | ------- | ------- | ------
overlay   |      1.0G | 5.9M |1019M |  1% |/
tmpfs   |         15G  |   0 |  15G  | 0% |/dev/shm
/dev/xvdb2  |    168G  | 28G | 132G  |18% |/tmp/garden-init
tmpfs      |      15G |    0  | 15G |  0%| /sys/fs/cgroup
udev        |     15G  |4.0K |  15G  | 1% |/dev/tty
tmpfs      |      15G  |   0  | 15G  | 0%| /proc/scsi

**Comment by AmyKort** [comment]
merged, so closing.
