### ISSUE TITLE
Add redirects for old election profile page links

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-proxy#88]
**What we're after:** After changing the design of the election profile pages, we changed the way data is organized in tabs on each election page. Unfortunately, the old links are still available and so we need to go back and add redirects for the old election profile page deep links.

The old links that are affected include: 
/?tab=totals
/?tab=contributions
/?tab=spending-by-others

This applies to all past /data/elections/senate, /house, and /president pages. 
Example: https://www.fec.gov/data/elections/president/2012/?tab=contributions

We should add redirects for the old election profile page deep links.

**Comment by AmyKort** [comment]
@patphongs  could you also take a look at this ticket to see if we need to update the work or the link?

**Comment by AmyKort** [comment]
Oh wait. Is this the ticket to update the links?

**Comment by patphongs** [comment]
@AmyKort Yes this is the one, I'm going to move it to fec-cms, since this actually needs to be done within the urls in python since nginx does not have the capabilities to pass arguments through to the resultant URL.

**Comment by patphongs** [comment]
Issue moved to [fecgov/fec-cms #2188](https://github.com/fecgov/fec-cms/issues/2188) via [**ZenHub**](https://www.zenhub.com/)
